import type { Role, RequestStatus, SaleStatus, Decision } from './domain'

export interface AppUserRow { id: string; tenant_id: string; role: Role; full_name: string; phone: string | null; is_active: boolean; email: string | null; language: string }
export interface CategoryRow { id: string; tenant_id: string; name: string; has_subcategories: boolean; name_i18n: Record<string, string> | null }
export interface SubcategoryRow { id: string; category_id: string; name: string; name_i18n: Record<string, string> | null }
export interface OperationTypeRow { id: string; category_id: string; subcategory_id: string | null; name: string; name_i18n: Record<string, string> | null }
export interface DoctorRow { id: string; tenant_id: string; app_user_id: string | null; photo_url: string | null; title: string | null; specialty: string | null; category_id: string; subcategory_id: string | null; bio: string | null; weighted_work: unknown; score: number; is_active: boolean }
export interface PatientRow { id: string; tenant_id: string; first_name: string; last_name: string; phone: string | null; email: string | null }
export interface RequestRow { id: string; tenant_id: string; patient_id: string; created_by: string; category_id: string; subcategory_id: string | null; operation_type_id: string | null; notes: string | null; status: RequestStatus; sale_status: SaleStatus; sale_marked_at: string | null; created_at: string; submitted_at: string | null; assigned_at: string | null; age: number | null; weight_kg: number | null; height_cm: number | null; gender: 'female' | 'male' | 'other' | null; past_surgeries: string; known_conditions: string; medications: string; photos_required: boolean; consent_at: string | null; consent_channel: string | null; consented_by: string | null; smoking_status: 'never' | 'former' | 'current' | null; smoking_cigs_per_day: number | null; smoking_years: number | null; smoking_pack_years: number | null; alcohol_status: 'never' | 'occasional' | 'regular' | null; alcohol_drinks_per_week: number | null; source_lang: string }
export interface PhotoRow { id: string; request_id: string; storage_path: string; uploaded_at: string; layer: 'active' | 'archive'; kind: 'photo' | 'xray'; deleted_at?: string | null; deletion_reason?: string | null }
export interface AssignmentRow { id: string; request_id: string; doctor_id: string; type: 'simultaneous' | 'manual'; assigned_at: string; seen_at: string | null }
export interface ResponseRow { id: string; request_id: string; doctor_id: string; decision: Decision; reject_reason: string | null; treatment_plan: string | null; responded_at: string; source_lang: string }
export interface DoctorScopeRow { id: string; tenant_id: string; doctor_id: string; category_id: string; subcategory_id: string | null }
export interface AiEvaluationRow { id: string; tenant_id: string; request_id: string; status: 'ok' | 'warning' | 'failed'; warnings: { type: string; confidence: number; rationale: string }[]; suitability_note: string | null; disclaimer: string; model: string; model_version: string | null; error: string | null; created_at: string }
export interface AiFeedbackRow { id: string; tenant_id: string; request_id: string; ai_evaluation_id: string; doctor_id: string; label: 'correct' | 'partial' | 'wrong'; note: string | null; created_at: string }
/** Faz 3: içerik çeviri önbelleği — client doğrudan erişmez (RLS: 0 satır); yalnız edge fn service-role ile. */
export interface ContentTranslationRow { id: string; tenant_id: string; source_hash: string; source_lang: string; target_lang: string; translated_text: string; created_at: string }
